### ISSUE TITLE
installed package not found with import

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdgeomkit#1]
## Expected behavior ##
I created a mamba virtual environment that contains MDAnalysis etc.

I created a package with MDA cookie cutter following https://mdakits.mdanalysis.org/makingakit.html#building-from-the-cookiecutter ; note that I chose *different names for the project/repo (`mdageomkit`) and the package (`mdgeom`)*.

When I install the package from the checked out sources into my environment with
```
python3 -m pip install .
```
and then try to import it (after moving out of the source directory)
```
cd ~
python
```
with
```python
import mdgeom
```
I expect the package to import without a problem.

## Actual behavior ##

```python
>>> import mdgeom
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'mdgeom'
```

Note that the `~/anaconda3/envs/workshop/lib/python3.12/site-packages/` directory *only* contains `mdgeomkit-0.0.1.dist-info` and NOT a corresponding `mdgeomkit` directory as for other packages.

## Code to reproduce the behavior ##

Install as above and then try
``` python
import mdgeomkit
```

## Current environment ##

- Which version are you using? (run `python -c "import mdgeomkit; print(mdgeomkit.__version__)"`): fails, should be 0.0.1
- Which version of Python (`python -V`)? Python 3.12.0
- Which operating system? macOS 13.6.6, Intel
- What is the output of `pip list`?
```
Package                   Version
------------------------- --------------
anyio                     4.3.0
appnope                   0.1.4
argon2-cffi               23.1.0
argon2-cffi-bindings      21.2.0
arrow                     1.3.0
asttokens                 2.4.1
async-lru                 2.0.4
attrs                     23.2.0
Babel                     2.14.0
beautifulsoup4            4.12.3
binaryornot               0.4.4
biopython                 1.83
bleach                    6.1.0
Brotli                    1.1.0
build                     0.7.0
cached-property           1.5.2
certifi                   2024.2.2
cffi                      1.16.0
cftime                    1.6.3
chardet                   5.2.0
charset-normalizer        3.3.2
click                     8.1.7
colorama                  0.4.6
comm                      0.2.2
contourpy                 1.2.1
cookiecutter              2.6.0
cycler                    0.12.1
debugpy                   1.8.1
decorator                 5.1.1
defusedxml                0.7.1
entrypoints               0.4
exceptiongroup            1.2.0
executing                 2.0.1
fasteners                 0.17.3
fastjsonschema            2.19.1
fonttools                 4.51.0
fqdn                      1.5.1
GridDataFormats           1.0.2
gsd                       3.2.1
h11                       0.14.0
h2                        4.1.0
h5py                      3.11.0
hpack                     4.0.0
httpcore                  1.0.5
httpx                     0.27.0
hyperframe                6.0.1
hypothesis                6.102.4
idna                      3.7
importlib_metadata        7.1.0
importlib_resources       6.4.0
iniconfig                 2.0.0
ipykernel                 6.29.3
ipython                   8.24.0
isoduration               20.11.0
jedi                      0.19.1
Jinja2                    3.1.4
joblib                    1.4.2
json5                     0.9.25
jsonpointer               2.4
jsonschema                4.22.0
jsonschema-specifications 2023.12.1
jupyter_client            8.6.1
jupyter_core              5.7.2
jupyter-events            0.10.0
jupyter-lsp               2.2.5
jupyter_server            2.14.0
jupyter_server_terminals  0.5.3
jupyterlab                4.2.0
jupyterlab_pygments       0.3.0
jupyterlab_server         2.27.1
kiwisolver                1.4.5
markdown-it-py            3.0.0
MarkupSafe                2.1.5
matplotlib                3.8.4
matplotlib-inline         0.1.7
mda-xdrlib                0.2.0
MDAnalysis                2.7.0
MDAnalysisTests           2.7.0
mdgeomkit                 0.0.1
mdurl                     0.1.2
mistune                   3.0.2
mmtf-python               1.1.3
mrcfile                   1.5.0
msgpack                   1.0.8
munkres                   1.1.4
nbclient                  0.10.0
nbconvert                 7.16.4
nbformat                  5.10.4
nest_asyncio              1.6.0
netCDF4                   1.6.5
networkx                  3.3
notebook_shim             0.2.4
numkit                    1.2.3
numpy                     1.26.4
overrides                 7.7.0
packaging                 24.0
pandas                    2.2.2
pandocfilters             1.5.0
parso                     0.8.4
patsy                     0.5.6
pep517                    0.13.0
pexpect                   4.9.0
pickleshare               0.7.5
pillow                    10.3.0
pip                       24.0
pkgutil_resolve_name      1.3.10
platformdirs              4.2.2
pluggy                    1.5.0
prettytable               3.10.0
prometheus_client         0.20.0
prompt-toolkit            3.0.42
psutil                    5.9.8
ptyprocess                0.7.0
pure-eval                 0.2.2
pycparser                 2.22
pyedr                     0.8.0
Pygments                  2.18.0
pyobjc-core               10.2
pyobjc-framework-Cocoa    10.2
pyparsing                 3.1.2
PySocks                   1.7.1
pytest                    8.2.1
python-dateutil           2.9.0
python-json-logger        2.0.7
python-slugify            8.0.4
pytng                     0.0.0
pytz                      2024.1
PyYAML                    6.0.1
pyzmq                     26.0.3
referencing               0.35.1
requests                  2.32.2
rfc3339-validator         0.1.4
rfc3986-validator         0.1.1
rich                      13.7.1
rpds-py                   0.18.1
scikit-learn              1.5.0
scipy                     1.13.0
seaborn                   0.13.2
Send2Trash                1.8.3
setuptools                70.0.0
six                       1.16.0
sniffio                   1.3.1
sortedcontainers          2.4.0
soupsieve                 2.5
stack-data                0.6.2
statsmodels               0.14.2
terminado                 0.18.1
text-unidecode            1.3
threadpoolctl             3.5.0
tidynamics                1.1.2
tinycss2                  1.3.0
tomli                     2.0.1
tornado                   6.4
tqdm                      4.66.4
traitlets                 5.14.3
types-python-dateutil     2.9.0.20240316
typing_extensions         4.11.0
typing-utils              0.1.0
tzdata                    2024.1
uri-template              1.3.0
urllib3                   2.2.1
wcwidth                   0.2.13
webcolors                 1.13
webencodings              0.5.1
websocket-client          1.8.0
wheel                     0.43.0
zipp                      3.17.0
```
- If you use conda, what is the output of `conda list`?
```
# packages in environment at ~/anaconda3/envs/workshop:
#
# Name                    Version                   Build  Channel
anyio                     4.3.0              pyhd8ed1ab_0    conda-forge
appnope                   0.1.4              pyhd8ed1ab_0    conda-forge
argon2-cffi               23.1.0             pyhd8ed1ab_0    conda-forge
argon2-cffi-bindings      21.2.0          py312h104f124_4    conda-forge
arrow                     1.3.0              pyhd8ed1ab_0    conda-forge
asttokens                 2.4.1              pyhd8ed1ab_0    conda-forge
async-lru                 2.0.4              pyhd8ed1ab_0    conda-forge
attrs                     23.2.0             pyh71513ae_0    conda-forge
babel                     2.14.0             pyhd8ed1ab_0    conda-forge
backports.zoneinfo        0.2.1           py312hb401068_8    conda-forge
beautifulsoup4            4.12.3             pyha770c72_0    conda-forge
binaryornot               0.4.4                      py_1    conda-forge
biopython                 1.83            py312h41838bb_0    conda-forge
bleach                    6.1.0              pyhd8ed1ab_0    conda-forge
blosc                     1.21.5               hafa3907_1    conda-forge
brotli                    1.1.0                h0dc2134_1    conda-forge
brotli-bin                1.1.0                h0dc2134_1    conda-forge
brotli-python             1.1.0           py312heafc425_1    conda-forge
build                     0.7.0              pyhd8ed1ab_0    conda-forge
bzip2                     1.0.8                h10d778d_5    conda-forge
c-ares                    1.28.1               h10d778d_0    conda-forge
ca-certificates           2024.2.2             h8857fd0_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
certifi                   2024.2.2           pyhd8ed1ab_0    conda-forge
cffi                      1.16.0          py312h38bf5a0_0    conda-forge
cftime                    1.6.3           py312h5dc8b90_1    conda-forge
chardet                   5.2.0           py312hb401068_1    conda-forge
charset-normalizer        3.3.2              pyhd8ed1ab_0    conda-forge
click                     8.1.7           unix_pyh707e725_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
comm                      0.2.2              pyhd8ed1ab_0    conda-forge
contourpy                 1.2.1           py312h9230928_0    conda-forge
cookiecutter              2.6.0              pyhca7485f_0    conda-forge
cycler                    0.12.1             pyhd8ed1ab_0    conda-forge
debugpy                   1.8.1           py312hede676d_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
exceptiongroup            1.2.0              pyhd8ed1ab_2    conda-forge
executing                 2.0.1              pyhd8ed1ab_0    conda-forge
fasteners                 0.17.3             pyhd8ed1ab_0    conda-forge
fonttools                 4.51.0          py312h41838bb_0    conda-forge
fqdn                      1.5.1              pyhd8ed1ab_0    conda-forge
freetype                  2.12.1               h60636b9_2    conda-forge
griddataformats           1.0.2              pyhd8ed1ab_0    conda-forge
gsd                       3.2.1           py312h5dc8b90_1    conda-forge
h11                       0.14.0             pyhd8ed1ab_0    conda-forge
h2                        4.1.0              pyhd8ed1ab_0    conda-forge
h5py                      3.11.0          nompi_py312hfc94b03_101    conda-forge
hdf4                      4.2.15               h8138101_7    conda-forge
hdf5                      1.14.3          nompi_hb512a33_101    conda-forge
hpack                     4.0.0              pyh9f0ad1d_0    conda-forge
httpcore                  1.0.5              pyhd8ed1ab_0    conda-forge
httpx                     0.27.0             pyhd8ed1ab_0    conda-forge
hyperframe                6.0.1              pyhd8ed1ab_0    conda-forge
hypothesis                6.102.4            pyha770c72_0    conda-forge
icu                       73.2                 hf5e326d_0    conda-forge
idna                      3.7                pyhd8ed1ab_0    conda-forge
importlib-metadata        7.1.0              pyha770c72_0    conda-forge
importlib_metadata        7.1.0                hd8ed1ab_0    conda-forge
importlib_resources       6.4.0              pyhd8ed1ab_0    conda-forge
iniconfig                 2.0.0              pyhd8ed1ab_0    conda-forge
ipykernel                 6.29.3             pyh3cd1d5f_0    conda-forge
ipython                   8.24.0             pyh707e725_0    conda-forge
isoduration               20.11.0            pyhd8ed1ab_0    conda-forge
jedi                      0.19.1             pyhd8ed1ab_0    conda-forge
jinja2                    3.1.4              pyhd8ed1ab_0    conda-forge
joblib                    1.4.2              pyhd8ed1ab_0    conda-forge
json5                     0.9.25             pyhd8ed1ab_0    conda-forge
jsonpointer               2.4             py312hb401068_3    conda-forge
jsonschema                4.22.0             pyhd8ed1ab_0    conda-forge
jsonschema-specifications 2023.12.1          pyhd8ed1ab_0    conda-forge
jsonschema-with-format-nongpl 4.22.0             pyhd8ed1ab_0    conda-forge
jupyter-lsp               2.2.5              pyhd8ed1ab_0    conda-forge
jupyter_client            8.6.1              pyhd8ed1ab_0    conda-forge
jupyter_core              5.7.2           py312hb401068_0    conda-forge
jupyter_events            0.10.0             pyhd8ed1ab_0    conda-forge
jupyter_server            2.14.0             pyhd8ed1ab_0    conda-forge
jupyter_server_terminals  0.5.3              pyhd8ed1ab_0    conda-forge
jupyterlab                4.2.0              pyhd8ed1ab_1    conda-forge
jupyterlab_pygments       0.3.0              pyhd8ed1ab_1    conda-forge
jupyterlab_server         2.27.1             pyhd8ed1ab_0    conda-forge
kiwisolver                1.4.5           py312h49ebfd2_1    conda-forge
krb5                      1.21.2               hb884880_0    conda-forge
lcms2                     2.16                 ha2f27b4_0    conda-forge
lerc                      4.0.0                hb486fe8_0    conda-forge
libaec                    1.1.3                h73e2aa4_0    conda-forge
libblas                   3.9.0           22_osx64_openblas    conda-forge
libbrotlicommon           1.1.0                h0dc2134_1    conda-forge
libbrotlidec              1.1.0                h0dc2134_1    conda-forge
libbrotlienc              1.1.0                h0dc2134_1    conda-forge
libcblas                  3.9.0           22_osx64_openblas    conda-forge
libcurl                   8.8.0                hf9fcc65_0    conda-forge
libcxx                    17.0.6               h88467a6_0    conda-forge
libdeflate                1.20                 h49d49c5_0    conda-forge
libedit                   3.1.20191231         h0678c8f_2    conda-forge
libev                     4.33                 h10d778d_2    conda-forge
libexpat                  2.6.2                h73e2aa4_0    conda-forge
libffi                    3.4.2                h0d85af4_5    conda-forge
libgfortran               5.0.0           13_2_0_h97931a8_3    conda-forge
libgfortran5              13.2.0               h2873a65_3    conda-forge
libiconv                  1.17                 hd75f5a5_2    conda-forge
libjpeg-turbo             3.0.0                h0dc2134_1    conda-forge
liblapack                 3.9.0           22_osx64_openblas    conda-forge
libnetcdf                 4.9.2           nompi_h7760872_113    conda-forge
libnghttp2                1.58.0               h64cf6d3_1    conda-forge
libopenblas               0.3.27          openmp_hfef2a42_0    conda-forge
libpng                    1.6.43               h92b6c6a_0    conda-forge
libsodium                 1.0.18               hbcb3906_1    conda-forge
libsqlite                 3.45.3               h92b6c6a_0    conda-forge
libssh2                   1.11.0               hd019ec5_0    conda-forge
libtiff                   4.6.0                h129831d_3    conda-forge
libwebp-base              1.4.0                h10d778d_0    conda-forge
libxcb                    1.15                 hb7f2c08_0    conda-forge
libxml2                   2.12.7               h3e169fe_0    conda-forge
libzip                    1.10.1               hc158999_3    conda-forge
libzlib                   1.2.13               h8a1eda9_5    conda-forge
llvm-openmp               18.1.5               h39e0ece_0    conda-forge
lz4-c                     1.9.4                hf0c8a7f_0    conda-forge
markdown-it-py            3.0.0              pyhd8ed1ab_0    conda-forge
markupsafe                2.1.5           py312h41838bb_0    conda-forge
matplotlib-base           3.8.4           py312hb6d62fa_2    conda-forge
matplotlib-inline         0.1.7              pyhd8ed1ab_0    conda-forge
mda-xdrlib                0.2.0              pyhd8ed1ab_0    conda-forge
mdanalysis                2.7.0           py312hb3462e8_1    conda-forge
mdanalysistests           2.7.0              pyhd8ed1ab_0    conda-forge
mdgeomkit                 0.0.1                    pypi_0    pypi
mdurl                     0.1.2              pyhd8ed1ab_0    conda-forge
mistune                   3.0.2              pyhd8ed1ab_0    conda-forge
mmtf-python               1.1.3              pyhd8ed1ab_0    conda-forge
mrcfile                   1.5.0              pyhd8ed1ab_0    conda-forge
msgpack-python            1.0.8           py312hc3c9ca0_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
nbclient                  0.10.0             pyhd8ed1ab_0    conda-forge
nbconvert-core            7.16.4             pyhd8ed1ab_0    conda-forge
nbformat                  5.10.4             pyhd8ed1ab_0    conda-forge
ncurses                   6.5                  h5846eda_0    conda-forge
nest-asyncio              1.6.0              pyhd8ed1ab_0    conda-forge
netcdf4                   1.6.5           nompi_py312hb3bfefa_101    conda-forge
networkx                  3.3                pyhd8ed1ab_1    conda-forge
notebook-shim             0.2.4              pyhd8ed1ab_0    conda-forge
numpy                     1.26.4          py312he3a82b2_0    conda-forge
openjpeg                  2.5.2                h7310d3a_0    conda-forge
openssl                   3.3.0                h87427d6_2    conda-forge
overrides                 7.7.0              pyhd8ed1ab_0    conda-forge
packaging                 24.0               pyhd8ed1ab_0    conda-forge
pandas                    2.2.2           py312h1171441_1    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
parso                     0.8.4              pyhd8ed1ab_0    conda-forge
patsy                     0.5.6              pyhd8ed1ab_0    conda-forge
pep517                    0.13.0             pyhd8ed1ab_0    conda-forge
pexpect                   4.9.0              pyhd8ed1ab_0    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    10.3.0          py312h0c923fa_0    conda-forge
pip                       24.0               pyhd8ed1ab_0    conda-forge
pkgutil-resolve-name      1.3.10             pyhd8ed1ab_1    conda-forge
platformdirs              4.2.2              pyhd8ed1ab_0    conda-forge
pluggy                    1.5.0              pyhd8ed1ab_0    conda-forge
prettytable               3.10.0             pyhd8ed1ab_0    conda-forge
prometheus_client         0.20.0             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.42             pyha770c72_0    conda-forge
psutil                    5.9.8           py312h41838bb_0    conda-forge
pthread-stubs             0.4               hc929b4f_1001    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
pycparser                 2.22               pyhd8ed1ab_0    conda-forge
pyedr                     0.8.0              pyhd8ed1ab_0    conda-forge
pygments                  2.18.0             pyhd8ed1ab_0    conda-forge
pyobjc-core               10.2            py312h74abf1d_0    conda-forge
pyobjc-framework-cocoa    10.2            py312h74abf1d_0    conda-forge
pyparsing                 3.1.2              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
pytest                    8.2.1              pyhd8ed1ab_0    conda-forge
python                    3.12.0          h30d4d87_0_cpython    conda-forge
python-dateutil           2.9.0              pyhd8ed1ab_0    conda-forge
python-fastjsonschema     2.19.1             pyhd8ed1ab_0    conda-forge
python-json-logger        2.0.7              pyhd8ed1ab_0    conda-forge
python-slugify            8.0.4              pyhd8ed1ab_0    conda-forge
python-tzdata             2024.1             pyhd8ed1ab_0    conda-forge
python_abi                3.12                    4_cp312    conda-forge
pytng                     0.3.1           py312h57167bd_2    conda-forge
pytz                      2024.1             pyhd8ed1ab_0    conda-forge
pyyaml                    6.0.1           py312h104f124_1    conda-forge
pyzmq                     26.0.3          py312ha04878a_0    conda-forge
readline                  8.2                  h9e318b2_1    conda-forge
referencing               0.35.1             pyhd8ed1ab_0    conda-forge
requests                  2.32.2             pyhd8ed1ab_0    conda-forge
rfc3339-validator         0.1.4              pyhd8ed1ab_0    conda-forge
rfc3986-validator         0.1.1              pyh9f0ad1d_0    conda-forge
rich                      13.7.1             pyhd8ed1ab_0    conda-forge
rpds-py                   0.18.1          py312ha47ea1c_0    conda-forge
scikit-learn              1.5.0           py312hc214ba5_0    conda-forge
scipy                     1.13.0          py312h741d2f9_1    conda-forge
seaborn                   0.13.2               hd8ed1ab_2    conda-forge
seaborn-base              0.13.2             pyhd8ed1ab_2    conda-forge
send2trash                1.8.3              pyh31c8845_0    conda-forge
setuptools                70.0.0             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.2.0                h6dc393e_1    conda-forge
sniffio                   1.3.1              pyhd8ed1ab_0    conda-forge
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
soupsieve                 2.5                pyhd8ed1ab_1    conda-forge
stack_data                0.6.2              pyhd8ed1ab_0    conda-forge
statsmodels               0.14.2          py312h5dc8b90_0    conda-forge
terminado                 0.18.1             pyh31c8845_0    conda-forge
text-unidecode            1.3                pyhd8ed1ab_1    conda-forge
threadpoolctl             3.5.0              pyhc1e730c_0    conda-forge
tidynamics                1.1.2              pyhd8ed1ab_0    conda-forge
tinycss2                  1.3.0              pyhd8ed1ab_0    conda-forge
tk                        8.6.13               h1abcd95_1    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
tornado                   6.4             py312h41838bb_0    conda-forge
tqdm                      4.66.4             pyhd8ed1ab_0    conda-forge
traitlets                 5.14.3             pyhd8ed1ab_0    conda-forge
types-python-dateutil     2.9.0.20240316     pyhd8ed1ab_0    conda-forge
typing-extensions         4.11.0               hd8ed1ab_0    conda-forge
typing_extensions         4.11.0             pyha770c72_0    conda-forge
typing_utils              0.1.0              pyhd8ed1ab_0    conda-forge
tzdata                    2024a                h0c530f3_0    conda-forge
uri-template              1.3.0              pyhd8ed1ab_0    conda-forge
urllib3                   2.2.1              pyhd8ed1ab_0    conda-forge
wcwidth                   0.2.13             pyhd8ed1ab_0    conda-forge
webcolors                 1.13               pyhd8ed1ab_0    conda-forge
webencodings              0.5.1              pyhd8ed1ab_2    conda-forge
websocket-client          1.8.0              pyhd8ed1ab_0    conda-forge
wheel                     0.43.0             pyhd8ed1ab_1    conda-forge
xorg-libxau               1.0.11               h0dc2134_0    conda-forge
xorg-libxdmcp             1.1.3                h35c211d_0    conda-forge
xz                        5.2.6                h775f41a_0    conda-forge
yaml                      0.2.5                h0d85af4_2    conda-forge
zeromq                    4.3.5                hde137ed_4    conda-forge
zipp                      3.17.0             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               h8a1eda9_5    conda-forge
zstd                      1.5.6                h915ae27_0    conda-forge
```

## Output from pip
(some paths sanitized as ~)
```
(workshop) deathstar:mdgeomkit oliver$ python3 -m pip install .
Processing ~/MDAnalysis/WorkshopMDAMolSSIASU/mdgeomkit
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: MDAnalysis>=2.0.0 in ~/anaconda3/envs/workshop/lib/python3.12/site-packages (from mdgeomkit==0.0.1) (2.7.0)
Requirement already satisfied: prettytable in ~/anaconda3/envs/workshop/lib/python3.12/site-packages (from mdgeomkit==0.0.1) (3.10.0)
Requirement already satisfied: numpy<2.0,>=1.22.3 in ~/anaconda3/envs/workshop/lib/python3.12/site-packages (from MDAnalysis>=2.0.0->mdgeomkit==0.0.1) (1.26.4)
Requirement already satisfied: GridDataFormats>=0.4.0 in ~/anaconda3/envs/workshop/lib/python3.12/site-packages (from MDAnalysis>=2.0.0->mdgeomkit==0.0.1) (1.0.2)
Requirement already satisfied: mmtf-python>=1.0.0 in ~/anaconda3/envs/workshop/lib/python3.12/site-packages (from MDAnalysis>=2.0.0->mdgeomkit==0.0.1) (1.1.3)
Requirement already satisfied: joblib>=0.12 in ~/anaconda3/envs/workshop/lib/python3.12/site-packages (from MDAnalysis>=2.0.0->mdgeomkit==0.0.1) (1.4.2)
Requirement already satisfied: scipy>=1.5.0 in ~/anaconda3/envs/workshop/lib/python3.12/site-packages (from MDAnalysis>=2.0.0->mdgeomkit==0.0.1) (1.13.0)
Requirement already satisfied: matplotlib>=1.5.1 in ~/anaconda3/envs/workshop/lib/python3.12/site-packages (from MDAnalysis>=2.0.0->mdgeomkit==0.0.1) (3.8.4)
Requirement already satisfied: tqdm>=4.43.0 in ~/anaconda3/envs/workshop/lib/python3.12/site-packages (from MDAnalysis>=2.0.0->mdgeomkit==0.0.1) (4.66.4)
Requirement already satisfied: threadpoolctl in ~/anaconda3/envs/workshop/lib/python3.12/site-packages (from MDAnalysis>=2.0.0->mdgeomkit==0.0.1) (3.5.0)
Requirement already satisfied: packaging in ~/anaconda3/envs/workshop/lib/python3.12/site-packages (from MDAnalysis>=2.0.0->mdgeomkit==0.0.1) (24.0)
Requirement already satisfied: fasteners in ~/anaconda3/envs/workshop/lib/python3.12/site-packages (from MDAnalysis>=2.0.0->mdgeomkit==0.0.1) (0.17.3)
Requirement already satisfied: mda-xdrlib in ~/anaconda3/envs/workshop/lib/python3.12/site-packages (from MDAnalysis>=2.0.0->mdgeomkit==0.0.1) (0.2.0)
Requirement already satisfied: wcwidth in ~/anaconda3/envs/workshop/lib/python3.12/site-packages (from prettytable->mdgeomkit==0.0.1) (0.2.13)
Requirement already satisfied: mrcfile in ~/anaconda3/envs/workshop/lib/python3.12/site-packages (from GridDataFormats>=0.4.0->MDAnalysis>=2.0.0->mdgeomkit==0.0.1) (1.5.0)
Requirement already satisfied: contourpy>=1.0.1 in ~/anaconda3/envs/workshop/lib/python3.12/site-packages (from matplotlib>=1.5.1->MDAnalysis>=2.0.0->mdgeomkit==0.0.1) (1.2.1)
Requirement already satisfied: cycler>=0.10 in ~/anaconda3/envs/workshop/lib/python3.12/site-packages (from matplotlib>=1.5.1->MDAnalysis>=2.0.0->mdgeomkit==0.0.1) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in ~/anaconda3/envs/workshop/lib/python3.12/site-packages (from matplotlib>=1.5.1->MDAnalysis>=2.0.0->mdgeomkit==0.0.1) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in ~/anaconda3/envs/workshop/lib/python3.12/site-packages (from matplotlib>=1.5.1->MDAnalysis>=2.0.0->mdgeomkit==0.0.1) (1.4.5)
Requirement already satisfied: pillow>=8 in ~/anaconda3/envs/workshop/lib/python3.12/site-packages (from matplotlib>=1.5.1->MDAnalysis>=2.0.0->mdgeomkit==0.0.1) (10.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in ~/anaconda3/envs/workshop/lib/python3.12/site-packages (from matplotlib>=1.5.1->MDAnalysis>=2.0.0->mdgeomkit==0.0.1) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in ~/anaconda3/envs/workshop/lib/python3.12/site-packages (from matplotlib>=1.5.1->MDAnalysis>=2.0.0->mdgeomkit==0.0.1) (2.9.0)
Requirement already satisfied: msgpack>=1.0.0 in ~/anaconda3/envs/workshop/lib/python3.12/site-packages (from mmtf-python>=1.0.0->MDAnalysis>=2.0.0->mdgeomkit==0.0.1) (1.0.8)
Requirement already satisfied: six>=1.5 in ~/anaconda3/envs/workshop/lib/python3.12/site-packages (from python-dateutil>=2.7->matplotlib>=1.5.1->MDAnalysis>=2.0.0->mdgeomkit==0.0.1) (1.16.0)
Building wheels for collected packages: mdgeomkit
  Building wheel for mdgeomkit (pyproject.toml) ... done
  Created wheel for mdgeomkit: filename=mdgeomkit-0.0.1-py3-none-any.whl size=17807 sha256=91094dc5193627ffddf6f9490b132f6a94c24fcb955f95d3e27e2da128996108
  Stored in directory: /private/var/folders/sm/37rm_wm16tq9qsf4n5md98ph0000gp/T/pip-ephem-wheel-cache-z3nwbcfu/wheels/a4/56/b1/fa2afce3a19bc3cd9a78c98924196742f1bfb5a27ac0750273
Successfully built mdgeomkit
Installing collected packages: mdgeomkit
Successfully installed mdgeomkit-0.0.1
```

**Comment by orbeckst** [comment]
@IAlibay any help is appreciated, at the moment I can't get the package to install properly.

**Comment by orbeckst** [comment]
I also tried building distributions with
```
python -m build 
```
and then installing the dist, 
```
pip install dist/mdgeomkit-0.0.1-py3-none-any.whl
```
with the same failure.

The sdist file does contains all the files that *should* be there
```
(workshop) deathstar:mdgeomkit oliver$ tar tvf dist/mdgeomkit-0.0.1.tar.gz
drwxr-xr-x  0 oliver staff       0 May 22 16:31 mdgeomkit-0.0.1/
-rw-r--r--  0 oliver staff     649 May 22 13:43 mdgeomkit-0.0.1/AUTHORS.md
-rw-r--r--  0 oliver staff     956 May 22 13:43 mdgeomkit-0.0.1/CHANGELOG.md
-rw-r--r--  0 oliver staff    7039 May 22 13:43 mdgeomkit-0.0.1/CODE_OF_CONDUCT.md
-rw-r--r--  0 oliver staff   18092 May 22 13:43 mdgeomkit-0.0.1/LICENSE
-rw-r--r--  0 oliver staff     152 May 22 13:43 mdgeomkit-0.0.1/MANIFEST.in
-rw-r--r--  0 oliver staff   26507 May 22 16:31 mdgeomkit-0.0.1/PKG-INFO
-rw-r--r--  0 oliver staff    4936 May 22 13:43 mdgeomkit-0.0.1/README.md
drwxr-xr-x  0 oliver staff       0 May 22 16:31 mdgeomkit-0.0.1/mdgeom/
-rw-r--r--  0 oliver staff     172 May 22 13:43 mdgeomkit-0.0.1/mdgeom/__init__.py
drwxr-xr-x  0 oliver staff       0 May 22 16:31 mdgeomkit-0.0.1/mdgeom/data/
-rw-r--r--  0 oliver staff    1005 May 22 13:43 mdgeomkit-0.0.1/mdgeom/data/README.md
-rw-r--r--  0 oliver staff       0 May 22 13:43 mdgeomkit-0.0.1/mdgeom/data/__init__.py
-rw-r--r--  0 oliver staff     279 May 22 13:43 mdgeomkit-0.0.1/mdgeom/data/files.py
-rw-r--r--  0 oliver staff    5920 May 22 13:43 mdgeomkit-0.0.1/mdgeom/data/mda.txt
-rw-r--r--  0 oliver staff    2746 May 22 14:48 mdgeomkit-0.0.1/mdgeom/info.py
drwxr-xr-x  0 oliver staff       0 May 22 16:31 mdgeomkit-0.0.1/mdgeom/tests/
-rw-r--r--  0 oliver staff       0 May 22 13:43 mdgeomkit-0.0.1/mdgeom/tests/__init__.py
-rw-r--r--  0 oliver staff     548 May 22 13:43 mdgeomkit-0.0.1/mdgeom/tests/conftest.py
-rw-r--r--  0 oliver staff    5027 May 22 15:26 mdgeomkit-0.0.1/mdgeom/tests/test_info.py
-rw-r--r--  0 oliver staff     535 May 22 13:43 mdgeomkit-0.0.1/mdgeom/tests/test_mdgeom.py
-rw-r--r--  0 oliver staff    2245 May 22 13:43 mdgeomkit-0.0.1/mdgeom/tests/utils.py
drwxr-xr-x  0 oliver staff       0 May 22 16:31 mdgeomkit-0.0.1/mdgeomkit.egg-info/
-rw-r--r--  0 oliver staff   26507 May 22 16:31 mdgeomkit-0.0.1/mdgeomkit.egg-info/PKG-INFO
-rw-r--r--  0 oliver staff     498 May 22 16:31 mdgeomkit-0.0.1/mdgeomkit.egg-info/SOURCES.txt
-rw-r--r--  0 oliver staff       1 May 22 16:31 mdgeomkit-0.0.1/mdgeomkit.egg-info/dependency_links.txt
-rw-r--r--  0 oliver staff     138 May 22 16:31 mdgeomkit-0.0.1/mdgeomkit.egg-info/requires.txt
-rw-r--r--  0 oliver staff       1 May 22 16:31 mdgeomkit-0.0.1/mdgeomkit.egg-info/top_level.txt
-rw-r--r--  0 oliver staff    1788 May 22 15:44 mdgeomkit-0.0.1/pyproject.toml
-rw-r--r--  0 oliver staff      38 May 22 16:31 mdgeomkit-0.0.1/setup.cfg
```

**Comment by IAlibay** [comment]
Very odd indeed, working on this.

**Comment by orbeckst** [comment]
Thank you! Given that it also fails in CI, it's probably not just a "me" problem.

The two things that may be an issue is that I chose different package and project names (as I said above) and _perhaps_ the use of UTF-8 characters and not being super-careful about file encodings.

**Comment by orbeckst** [comment]
I tried following the tutorial https://mdakits.mdanalysis.org/makingakit.html#building-from-the-cookiecutter word for word, including creating the environment later (just before `pip install -e .`) and I also get a import error
```
(rmsfkit) deathstar:tmp oliver$ python
Python 3.12.0 | packaged by conda-forge | (main, Oct  3 2023, 08:43:38) [Clang 15.0.7 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import rmsfkit
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'rmsfkit'
>>>
```
The only relevant dir I can find in `~/anaconda3/envs/rmsfkit/lib/python3.12/site-packages/` is `rmsfkit-0.0.0+3.g28a9cd7.dist-info`.

**Comment by orbeckst** [comment]
It's not the difference between package and project name. For the rmsfkit I chose the same and it still is not working in the way described above (and now in https://github.com/MDAnalysis/cookiecutter-mdakit/issues/113). This looks like a more general issue with either our tutorial or the cookie-cutter - or something else in the tool chain.
